version: '3'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: runtime
    container_name: fastapi
    image: pierrechavez/fastapi:0.0.3
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3000"