version: '3'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: runtime
    container_name: fastapi
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"